{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"fillWasCanceled"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userCanceledFill"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cursorPosition"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ioInsertionPointLocation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/smthirdviewcontroller\/makeidentifiedtextobjectfirstresponder(_:fillwascanceled:cursorposition:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/smthirdviewcontroller\/makeidentifiedtextobjectfirstresponder(_:fillwascanceled:cursorposition:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMThirdViewController\/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SMTEFillDelegate.makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"fillWasCanceled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cursorPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"title":"makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TextExpanderDemoAppSwift@objc(cs)SMThirdViewController(im)makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMThirdViewController"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMThirdViewController":{"role":"symbol","title":"SMThirdViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMThirdViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMThirdViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMThirdViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smthirdviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMThirdViewController/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)":{"role":"symbol","title":"makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"fillWasCanceled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cursorPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMThirdViewController\/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"}],"url":"\/documentation\/textexpanderdemoappswift\/smthirdviewcontroller\/makeidentifiedtextobjectfirstresponder(_:fillwascanceled:cursorposition:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"textIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"fillWasCanceled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"userCanceledFill"},{"kind":"text","text":" "},{"kind":"identifier","text":"cursorPosition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"ioInsertionPointLocation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMThirdViewController\/title","value":"SMThirdViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMThirdViewController\/fragments","value":[{"kind":"identifier","text":"SMThirdViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMThirdViewController~1makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)\/title","value":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMThirdViewController~1makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}