{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webViewDidFinishLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inWebView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWebView","preciseIdentifier":"c:objc(cs)UIWebView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/smthirdviewcontroller\/webviewdidfinishload(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/smthirdviewcontroller\/webviewdidfinishload(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMThirdViewController\/webViewDidFinishLoad(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIWebViewDelegate.webViewDidFinishLoad(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webViewDidFinishLoad"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIWebView","preciseIdentifier":"c:objc(cs)UIWebView"},{"kind":"text","text":")"}],"title":"webViewDidFinishLoad(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TextExpanderDemoAppSwift@objc(cs)SMThirdViewController(im)webViewDidFinishLoad:","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"webViewDidFinishLoad:"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMThirdViewController"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMThirdViewController":{"role":"symbol","title":"SMThirdViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMThirdViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMThirdViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMThirdViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smthirdviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMThirdViewController/webViewDidFinishLoad(_:)":{"role":"symbol","title":"webViewDidFinishLoad(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webViewDidFinishLoad"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIWebView","preciseIdentifier":"c:objc(cs)UIWebView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMThirdViewController\/webViewDidFinishLoad(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webViewDidFinishLoad:"}],"url":"\/documentation\/textexpanderdemoappswift\/smthirdviewcontroller\/webviewdidfinishload(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"webViewDidFinishLoad:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webViewDidFinishLoad:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"webViewDidFinishLoad:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIWebView","preciseIdentifier":"c:objc(cs)UIWebView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"inWebView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMThirdViewController\/title","value":"SMThirdViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMThirdViewController\/fragments","value":[{"kind":"identifier","text":"SMThirdViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMThirdViewController~1webViewDidFinishLoad(_:)\/title","value":"webViewDidFinishLoad:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMThirdViewController~1webViewDidFinishLoad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webViewDidFinishLoad:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}