{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMFirstViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSCoding","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSObject","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMTextExpanderViewController","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s7CVarArgP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s28CustomDebugStringConvertibleP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s23CustomStringConvertibleP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SQ","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SH","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s8SendableP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)SMTEFillDelegate","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIAppearanceContainer","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIContentContainer","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIFocusEnvironment","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIStateRestoring","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITraitEnvironment","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/searchBar","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/snippetExpanded","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/tapRecognizer","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textExpander","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textField","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/didReceiveMemoryWarning()","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/didTapAnywhere(recognizer:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/identifier(forTextArea:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/keyboardWillHide(note:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/keyboardWillShow(note:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/prepareForFillSwitch(textIdentifier:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/searchBarCancelButtonClicked(inSearchBar:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/setupKeyboardDismissal()","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textField(aTextField:shouldChangeCharactersInRange:replacementString:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldDidBeginEditing(textField:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldDidEndEditing(textField:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldShouldBeginEditing(textField:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldShouldClear(textField:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldShouldEndEditing(textField:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldShouldReturn(textField:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textView(aTextView:shouldChangeTextInRange:replacementText:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewDidBeginEditing(textView:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewDidChange(textView:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewDidChangeSelection(textView:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewDidEndEditing(textView:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewShouldBeginEditing(textView:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewShouldEndEditing(textView:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/viewDidLoad()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMFirstViewController"}],"title":"SMFirstViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TextExpanderDemoAppSwift@objc(cs)SMFirstViewController","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"SMFirstViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/prepareForFillSwitch(textIdentifier:)":{"role":"symbol","title":"prepareForFillSwitch(textIdentifier:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForFillSwitch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/prepareForFillSwitch(textIdentifier:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/prepareforfillswitch(textidentifier:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/setupKeyboardDismissal()":{"role":"symbol","title":"setupKeyboardDismissal()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupKeyboardDismissal"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/setupKeyboardDismissal()","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/setupkeyboarddismissal()"},"doc://com.extratone.TextExpanderDemoAppSwift/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s7CVarArgP"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/searchBar":{"role":"symbol","title":"searchBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/searchBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"searchBar"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/searchbar"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textFieldShouldReturn(textField:)":{"role":"symbol","title":"textFieldShouldReturn(textField:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldReturn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldShouldReturn(textField:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textfieldshouldreturn(textfield:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/initwithcoder:"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textFieldDidEndEditing(textField:)":{"role":"symbol","title":"textFieldDidEndEditing(textField:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDidEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldDidEndEditing(textField:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textfielddidendediting(textfield:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)":{"role":"symbol","title":"makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"fillWasCanceled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cursorPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/makeidentifiedtextobjectfirstresponder(_:fillwascanceled:cursorposition:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textFieldDidBeginEditing(textField:)":{"role":"symbol","title":"textFieldDidBeginEditing(textField:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDidBeginEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldDidBeginEditing(textField:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textfielddidbeginediting(textfield:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textViewDidChangeSelection(textView:)":{"role":"symbol","title":"textViewDidChangeSelection(textView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidChangeSelection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewDidChangeSelection(textView:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textviewdidchangeselection(textview:)"},"doc://com.extratone.TextExpanderDemoAppSwift/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SH"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/identifier(forTextArea:)":{"role":"symbol","title":"identifier(forTextArea:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTextArea"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/identifier(forTextArea:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"identifierForTextArea:"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/identifier(fortextarea:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textFieldShouldEndEditing(textField:)":{"role":"symbol","title":"textFieldShouldEndEditing(textField:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldShouldEndEditing(textField:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textfieldshouldendediting(textfield:)"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSObject"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/keyboardWillHide(note:)":{"role":"symbol","title":"keyboardWillHide(note:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardWillHide"},{"kind":"text","text":"("},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/keyboardWillHide(note:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keyboardWillHideWithNote:"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/keyboardwillhide(note:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textExpander":{"role":"symbol","title":"textExpander","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textExpander"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SMTEDelegateController","preciseIdentifier":"c:objc(cs)SMTEDelegateController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textExpander","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textexpander"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSCoding"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textViewShouldBeginEditing(textView:)":{"role":"symbol","title":"textViewShouldBeginEditing(textView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewShouldBeginEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewShouldBeginEditing(textView:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textviewshouldbeginediting(textview:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textView":{"role":"symbol","title":"textView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textView"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textview"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSExtensionRequestHandling"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textField":{"role":"symbol","title":"textField","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textField"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textfield"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMTextExpanderViewController":{"role":"symbol","title":"SMTextExpanderViewController","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMTextExpanderViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMTextExpanderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMTextExpanderViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smtextexpanderviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIUserActivityRestoring"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIStateRestoring"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textViewDidBeginEditing(textView:)":{"role":"symbol","title":"textViewDidBeginEditing(textView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidBeginEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewDidBeginEditing(textView:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textviewdidbeginediting(textview:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/didTapAnywhere(recognizer:)":{"role":"symbol","title":"didTapAnywhere(recognizer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapAnywhere"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/didTapAnywhere(recognizer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didTapAnywhereWithRecognizer:"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/didtapanywhere(recognizer:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textFieldShouldBeginEditing(textField:)":{"role":"symbol","title":"textFieldShouldBeginEditing(textField:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldBeginEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldShouldBeginEditing(textField:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textfieldshouldbeginediting(textfield:)"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIFocusEnvironment"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/snippetExpanded":{"role":"symbol","title":"snippetExpanded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"snippetExpanded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/snippetExpanded","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/snippetexpanded"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIResponderStandardEditActions"},"doc://com.extratone.TextExpanderDemoAppSwift/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s8SendableP"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textViewDidEndEditing(textView:)":{"role":"symbol","title":"textViewDidEndEditing(textView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewDidEndEditing(textView:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textviewdidendediting(textview:)"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIAppearanceContainer"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/initwithnibname:bundle:"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)UIViewController"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)SMTEFillDelegate":{"type":"unresolvable","title":"SMTEFillDelegate","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)SMTEFillDelegate"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textView(aTextView:shouldChangeTextInRange:replacementText:)":{"role":"symbol","title":"textView(aTextView:shouldChangeTextInRange:replacementText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"aTextView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeTextInRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textView(aTextView:shouldChangeTextInRange:replacementText:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textview(atextview:shouldchangetextinrange:replacementtext:)"},"doc://com.extratone.TextExpanderDemoAppSwift/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s28CustomDebugStringConvertibleP"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/viewdidload()"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/keyboardWillShow(note:)":{"role":"symbol","title":"keyboardWillShow(note:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardWillShow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"note"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNotification","preciseIdentifier":"c:objc(cs)NSNotification"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/keyboardWillShow(note:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keyboardWillShowWithNote:"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/keyboardwillshow(note:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textViewShouldEndEditing(textView:)":{"role":"symbol","title":"textViewShouldEndEditing(textView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewShouldEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewShouldEndEditing(textView:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textviewshouldendediting(textview:)"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITraitEnvironment"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIContentContainer"},"doc://com.extratone.TextExpanderDemoAppSwift/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SQ"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/tapRecognizer":{"role":"symbol","title":"tapRecognizer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tapRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/tapRecognizer","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/taprecognizer"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/searchBarCancelButtonClicked(inSearchBar:)":{"role":"symbol","title":"searchBarCancelButtonClicked(inSearchBar:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchBarCancelButtonClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inSearchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/searchBarCancelButtonClicked(inSearchBar:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/searchbarcancelbuttonclicked(insearchbar:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController":{"role":"symbol","title":"SMFirstViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMFirstViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMFirstViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s23CustomStringConvertibleP"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/didReceiveMemoryWarning()":{"role":"symbol","title":"didReceiveMemoryWarning()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveMemoryWarning"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/didReceiveMemoryWarning()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveMemoryWarning"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/didreceivememorywarning()"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textFieldShouldClear(textField:)":{"role":"symbol","title":"textFieldShouldClear(textField:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldClear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textFieldShouldClear(textField:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textfieldshouldclear(textfield:)"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textViewDidChange(textView:)":{"role":"symbol","title":"textViewDidChange(textView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textViewDidChange(textView:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textviewdidchange(textview:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/textField(aTextField:shouldChangeCharactersInRange:replacementString:)":{"role":"symbol","title":"textField(aTextField:shouldChangeCharactersInRange:replacementString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"aTextField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersInRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textField(aTextField:shouldChangeCharactersInRange:replacementString:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/textfield(atextfield:shouldchangecharactersinrange:replacementstring:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SMFirstViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMFirstViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMFirstViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/searchBar","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textField","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/textView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/didReceiveMemoryWarning()","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/didTapAnywhere(recognizer:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/identifier(forTextArea:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/initWithCoder:","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/initWithNibName:bundle:","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/keyboardWillHide(note:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/keyboardWillShow(note:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)SMTEFillDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMFirstViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1searchBar\/title","value":"searchBar"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1searchBar\/fragments","value":[{"kind":"identifier","text":"searchBar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)\/title","value":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1identifier(forTextArea:)\/title","value":"identifierForTextArea:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1identifier(forTextArea:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"identifierForTextArea:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1keyboardWillHide(note:)\/title","value":"keyboardWillHideWithNote:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1keyboardWillHide(note:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"keyboardWillHideWithNote:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1textView\/title","value":"textView"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1textView\/fragments","value":[{"kind":"identifier","text":"textView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1textField\/title","value":"textField"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1textField\/fragments","value":[{"kind":"identifier","text":"textField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1didTapAnywhere(recognizer:)\/title","value":"didTapAnywhereWithRecognizer:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1didTapAnywhere(recognizer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapAnywhereWithRecognizer:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1keyboardWillShow(note:)\/title","value":"keyboardWillShowWithNote:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1keyboardWillShow(note:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"keyboardWillShowWithNote:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController\/title","value":"SMFirstViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController\/fragments","value":[{"kind":"identifier","text":"SMFirstViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1didReceiveMemoryWarning()\/title","value":"didReceiveMemoryWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1didReceiveMemoryWarning()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveMemoryWarning"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}