{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSettingsViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)UITableViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSCoding","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSObject","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMTextExpanderViewController","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s7CVarArgP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s28CustomDebugStringConvertibleP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s23CustomStringConvertibleP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SQ","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SH","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s8SendableP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIAppearanceContainer","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIContentContainer","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIFocusEnvironment","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIScrollViewDelegate","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIStateRestoring","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITableViewDataSource","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITableViewDelegate","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITraitEnvironment","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/blankCell","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/textExpander","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/textExpanderToggle","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/textExpanderToggleCell","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/textExpanderUpdateCell"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/didReceiveMemoryWarning()","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/switchAction(sender:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/tableView(_:didSelectRowAt:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/tableView(_:numberOfRowsInSection:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/updateCells()","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/viewDidAppear(_:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/viewDidLoad()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/SMTESettingsViewCellIndex"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSettingsViewController"}],"title":"SMSettingsViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TextExpanderDemoAppSwift@objc(cs)SMSettingsViewController","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"SMSettingsViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIUserActivityRestoring"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/initwithcoder:"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/switchAction(sender:)":{"role":"symbol","title":"switchAction(sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyObject","preciseIdentifier":"s:s9AnyObjecta"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/switchAction(sender:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchActionWithSender:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/switchaction(sender:)"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(cs)UITableViewController":{"type":"unresolvable","title":"UITableViewController","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)UITableViewController"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIContentContainer"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/viewdidappear(_:)"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIAppearanceContainer"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/initwithnibname:bundle:"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/textExpanderUpdateCell":{"role":"symbol","title":"textExpanderUpdateCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textExpanderUpdateCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/textExpanderUpdateCell","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/textexpanderupdatecell"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/tableView(_:cellForRowAt:)":{"role":"symbol","title":"tableView(_:cellForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/tableView(_:cellForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/tableview(_:cellforrowat:)"},"doc://com.extratone.TextExpanderDemoAppSwift/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s7CVarArgP"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIScrollViewDelegate"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/initWithStyle:":{"role":"symbol","title":"initWithStyle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/initWithStyle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/initwithstyle:"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/textExpanderToggle":{"role":"symbol","title":"textExpanderToggle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textExpanderToggle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISwitch","preciseIdentifier":"c:objc(cs)UISwitch"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/textExpanderToggle","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/textexpandertoggle"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/didReceiveMemoryWarning()":{"role":"symbol","title":"didReceiveMemoryWarning()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveMemoryWarning"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/didReceiveMemoryWarning()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveMemoryWarning"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/didreceivememorywarning()"},"doc://com.extratone.TextExpanderDemoAppSwift/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SH"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/textExpander":{"role":"symbol","title":"textExpander","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textExpander"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SMTEDelegateController","preciseIdentifier":"c:objc(cs)SMTEDelegateController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/textExpander","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/textexpander"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/SMTESettingsViewCellIndex":{"role":"symbol","title":"SMSettingsViewController.SMTESettingsViewCellIndex","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMTESettingsViewCellIndex"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/SMTESettingsViewCellIndex","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMTESettingsViewCellIndex"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/smtesettingsviewcellindex"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/updateCells()":{"role":"symbol","title":"updateCells()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCells"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/updateCells()","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/updatecells()"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSObject"},"doc://com.extratone.TextExpanderDemoAppSwift/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SQ"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/blankCell":{"role":"symbol","title":"blankCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blankCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/blankCell","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/blankcell"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIResponderStandardEditActions"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSCoding"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/textExpanderToggleCell":{"role":"symbol","title":"textExpanderToggleCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textExpanderToggleCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/textExpanderToggleCell","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/textexpandertogglecell"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITraitEnvironment"},"doc://com.extratone.TextExpanderDemoAppSwift/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s28CustomDebugStringConvertibleP"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UIKit.UITableViewDataSource","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITableViewDataSource"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMTextExpanderViewController":{"role":"symbol","title":"SMTextExpanderViewController","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMTextExpanderViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMTextExpanderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMTextExpanderViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smtextexpanderviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UIKit.UITableViewDelegate","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITableViewDelegate"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController":{"role":"symbol","title":"SMSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMSettingsViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIFocusEnvironment"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/tableView(_:numberOfRowsInSection:)":{"role":"symbol","title":"tableView(_:numberOfRowsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/tableView(_:numberOfRowsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/tableview(_:numberofrowsinsection:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/tableView(_:didSelectRowAt:)":{"role":"symbol","title":"tableView(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/tableView(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/tableview(_:didselectrowat:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSettingsViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/textexpanderdemoappswift\/smsettingsviewcontroller\/viewdidload()"},"doc://com.extratone.TextExpanderDemoAppSwift/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s23CustomStringConvertibleP"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSExtensionRequestHandling"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIStateRestoring"},"doc://com.extratone.TextExpanderDemoAppSwift/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SMSettingsViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMSettingsViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMSettingsViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/didReceiveMemoryWarning()","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/initWithCoder:","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/initWithNibName:bundle:","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/initWithStyle:","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/switchAction(sender:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/tableView(_:didSelectRowAt:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/tableView(_:numberOfRowsInSection:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/viewDidAppear(_:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSettingsViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)UITableViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSettingsViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITableViewController","preciseIdentifier":"c:objc(cs)UITableViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1switchAction(sender:)\/title","value":"switchActionWithSender:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1switchAction(sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchActionWithSender:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1tableView(_:cellForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1didReceiveMemoryWarning()\/title","value":"didReceiveMemoryWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1didReceiveMemoryWarning()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveMemoryWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController\/title","value":"SMSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SMSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1tableView(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSettingsViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}