{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSecondViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSCoding","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSObject","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMTextExpanderViewController","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s7CVarArgP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s28CustomDebugStringConvertibleP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s23CustomStringConvertibleP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SQ","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SH","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s8SendableP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)SMTEFillDelegate","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIAppearanceContainer","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIContentContainer","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIFocusEnvironment","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIStateRestoring","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITraitEnvironment","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/textExpander","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/webView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/didReceiveMemoryWarning()","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/identifier(forTextArea:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/prepareForFillSwitch(textIdentifier:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/viewDidLoad()","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/webView(webView:didFailLoadWithError:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/webViewDidFinishLoad(inWebView:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/webViewDidStartLoad(webView:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSecondViewController"}],"title":"SMSecondViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@TextExpanderDemoAppSwift@objc(cs)SMSecondViewController","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"SMSecondViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/webView(webView:didFailLoadWithError:)":{"role":"symbol","title":"webView(webView:didFailLoadWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWebView","preciseIdentifier":"c:objc(cs)UIWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailLoadWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/webView(webView:didFailLoadWithError:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/webview(webview:didfailloadwitherror:)"},"doc://com.extratone.TextExpanderDemoAppSwift/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s8SendableP"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/prepareForFillSwitch(textIdentifier:)":{"role":"symbol","title":"prepareForFillSwitch(textIdentifier:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForFillSwitch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"textIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/prepareForFillSwitch(textIdentifier:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/prepareforfillswitch(textidentifier:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/viewdidload()"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIResponderStandardEditActions"},"doc://com.extratone.TextExpanderDemoAppSwift/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s7CVarArgP"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/didReceiveMemoryWarning()":{"role":"symbol","title":"didReceiveMemoryWarning()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveMemoryWarning"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/didReceiveMemoryWarning()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didReceiveMemoryWarning"}],"url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/didreceivememorywarning()"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)":{"role":"symbol","title":"makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"fillWasCanceled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cursorPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":">) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/makeidentifiedtextobjectfirstresponder(_:fillwascanceled:cursorposition:)"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIContentContainer"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSExtensionRequestHandling"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSCoding"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/webViewDidFinishLoad(inWebView:)":{"role":"symbol","title":"webViewDidFinishLoad(inWebView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webViewDidFinishLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"inWebView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWebView","preciseIdentifier":"c:objc(cs)UIWebView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/webViewDidFinishLoad(inWebView:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/webviewdidfinishload(inwebview:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMTextExpanderViewController":{"role":"symbol","title":"SMTextExpanderViewController","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMTextExpanderViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMTextExpanderViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMTextExpanderViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smtextexpanderviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SH"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIFocusEnvironment"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/initwithnibname:bundle:"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIStateRestoring"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/webView":{"role":"symbol","title":"webView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWebView","preciseIdentifier":"c:objc(cs)UIWebView"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/webView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView"}],"url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/webview"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UITraitEnvironment"},"doc://com.extratone.TextExpanderDemoAppSwift/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s28CustomDebugStringConvertibleP"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)SMTEFillDelegate":{"type":"unresolvable","title":"SMTEFillDelegate","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)SMTEFillDelegate"},"doc://com.extratone.TextExpanderDemoAppSwift/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s23CustomStringConvertibleP"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)UIViewController"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/initwithcoder:"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController":{"role":"symbol","title":"SMSecondViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSecondViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMSecondViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SQ"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/identifier(forTextArea:)":{"role":"symbol","title":"identifier(forTextArea:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTextArea"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/identifier(forTextArea:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"identifierForTextArea:"}],"url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/identifier(fortextarea:)"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIUserActivityRestoring"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/webViewDidStartLoad(webView:)":{"role":"symbol","title":"webViewDidStartLoad(webView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webViewDidStartLoad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIWebView","preciseIdentifier":"c:objc(cs)UIWebView"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/webViewDidStartLoad(webView:)","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/webviewdidstartload(webview:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSecondViewController/textExpander":{"role":"symbol","title":"textExpander","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textExpander"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SMTEDelegateController","preciseIdentifier":"c:objc(cs)SMTEDelegateController"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/textExpander","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift\/smsecondviewcontroller\/textexpander"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)UIAppearanceContainer"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SMSecondViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMSecondViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMSecondViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/webView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/didReceiveMemoryWarning()","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/identifier(forTextArea:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/initWithCoder:","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/initWithNibName:bundle:","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSecondViewController\/viewDidLoad()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)SMTEFillDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSecondViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1didReceiveMemoryWarning()\/title","value":"didReceiveMemoryWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1didReceiveMemoryWarning()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didReceiveMemoryWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)\/title","value":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1makeIdentifiedTextObjectFirstResponder(_:fillWasCanceled:cursorPosition:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeIdentifiedTextObjectFirstResponder:fillWasCanceled:cursorPosition:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1webView\/title","value":"webView"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1webView\/fragments","value":[{"kind":"identifier","text":"webView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController\/title","value":"SMSecondViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController\/fragments","value":[{"kind":"identifier","text":"SMSecondViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1identifier(forTextArea:)\/title","value":"identifierForTextArea:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSecondViewController~1identifier(forTextArea:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"identifierForTextArea:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}