{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSwiftWorkarounds"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/smswiftworkarounds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/smswiftworkarounds"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSObject","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s7CVarArgP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s28CustomDebugStringConvertibleP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s23CustomStringConvertibleP","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SQ","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSwiftWorkarounds","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSwiftWorkarounds\/disableCustomKeyboardExpansion()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSwiftWorkarounds"}],"title":"SMSwiftWorkarounds","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SMSwiftWorkarounds","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"SMSwiftWorkarounds"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(pl)NSObject"},"doc://com.extratone.TextExpanderDemoAppSwift/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s28CustomDebugStringConvertibleP"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSwiftWorkarounds/disableCustomKeyboardExpansion()":{"role":"symbol","title":"disableCustomKeyboardExpansion()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disableCustomKeyboardExpansion"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSwiftWorkarounds\/disableCustomKeyboardExpansion()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"disableCustomKeyboardExpansion"}],"url":"\/documentation\/textexpanderdemoappswift\/smswiftworkarounds\/disablecustomkeyboardexpansion()"},"doc://com.extratone.TextExpanderDemoAppSwift/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SQ"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMSwiftWorkarounds":{"role":"symbol","title":"SMSwiftWorkarounds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSwiftWorkarounds"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSwiftWorkarounds","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMSwiftWorkarounds"}],"url":"\/documentation\/textexpanderdemoappswift\/smswiftworkarounds"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"},"doc://com.extratone.TextExpanderDemoAppSwift/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s7CVarArgP"},"doc://com.extratone.TextExpanderDemoAppSwift/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/s23CustomStringConvertibleP"},"doc://com.extratone.TextExpanderDemoAppSwift/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/SH"},"doc://com.extratone.TextExpanderDemoAppSwift/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SMSwiftWorkarounds"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SMSwiftWorkarounds"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SMSwiftWorkarounds"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMSwiftWorkarounds\/disableCustomKeyboardExpansion()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMSwiftWorkarounds"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSwiftWorkarounds~1disableCustomKeyboardExpansion()\/title","value":"disableCustomKeyboardExpansion"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSwiftWorkarounds~1disableCustomKeyboardExpansion()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"disableCustomKeyboardExpansion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSwiftWorkarounds\/title","value":"SMSwiftWorkarounds"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMSwiftWorkarounds\/fragments","value":[{"kind":"identifier","text":"SMSwiftWorkarounds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}