{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapAnywhere"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/didtapanywhere(recognizer:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/didtapanywhere(recognizer:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/didTapAnywhere(recognizer:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapAnywhere"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"title":"didTapAnywhere(recognizer:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TextExpanderDemoAppSwift@objc(cs)SMFirstViewController(im)didTapAnywhereWithRecognizer:","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"didTapAnywhereWithRecognizer:"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController":{"role":"symbol","title":"SMFirstViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMFirstViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMFirstViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/didTapAnywhere(recognizer:)":{"role":"symbol","title":"didTapAnywhere(recognizer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapAnywhere"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/didTapAnywhere(recognizer:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didTapAnywhereWithRecognizer:"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/didtapanywhere(recognizer:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didTapAnywhereWithRecognizer:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapAnywhereWithRecognizer:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didTapAnywhereWithRecognizer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"recognizer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController\/title","value":"SMFirstViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController\/fragments","value":[{"kind":"identifier","text":"SMFirstViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1didTapAnywhere(recognizer:)\/title","value":"didTapAnywhereWithRecognizer:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1didTapAnywhere(recognizer:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapAnywhereWithRecognizer:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}