{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTextArea"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uiTextObject"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/identifier(fortextarea:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/identifier(fortextarea:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/identifier(forTextArea:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SMTEFillDelegate.identifier(forTextArea:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTextArea"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"title":"identifier(forTextArea:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TextExpanderDemoAppSwift@objc(cs)SMFirstViewController(im)identifierForTextArea:","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"identifierForTextArea:"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController":{"role":"symbol","title":"SMFirstViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SMFirstViewController"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SMFirstViewController"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/SMFirstViewController/identifier(forTextArea:)":{"role":"symbol","title":"identifier(forTextArea:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forTextArea"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"!) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/SMFirstViewController\/identifier(forTextArea:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"identifierForTextArea:"}],"url":"\/documentation\/textexpanderdemoappswift\/smfirstviewcontroller\/identifier(fortextarea:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"identifierForTextArea:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"identifierForTextArea:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"identifierForTextArea:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"uiTextObject"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController\/title","value":"SMFirstViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController\/fragments","value":[{"kind":"identifier","text":"SMFirstViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1identifier(forTextArea:)\/title","value":"identifierForTextArea:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1SMFirstViewController~1identifier(forTextArea:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"identifierForTextArea:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}