{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"application"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"kind":"text","text":" "},{"kind":"internalParam","text":"launchOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? = nil) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/appdelegate\/application(_:didfinishlaunchingwithoptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/appdelegate\/application(_:didfinishlaunchingwithoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIApplicationDelegate.application(_:didFinishLaunchingWithOptions:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"application(_:didFinishLaunchingWithOptions:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TextExpanderDemoAppSwift@objc(cs)AppDelegate(im)application:didFinishLaunchingWithOptions:","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/AppDelegate"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/AppDelegate/application(_:didFinishLaunchingWithOptions:)":{"role":"symbol","title":"application(_:didFinishLaunchingWithOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishLaunchingWithOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"LaunchOptionsKey","preciseIdentifier":"c:@T@UIApplicationLaunchOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/AppDelegate\/application(_:didFinishLaunchingWithOptions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}],"url":"\/documentation\/textexpanderdemoappswift\/appdelegate\/application(_:didfinishlaunchingwithoptions:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/textexpanderdemoappswift\/appdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"application:didFinishLaunchingWithOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"application"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishLaunchingWithOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"launchOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/title","value":"application:didFinishLaunchingWithOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1AppDelegate~1application(_:didFinishLaunchingWithOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:didFinishLaunchingWithOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}