{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"app"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"open"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"OpenURLOptionsKey","preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] = [:]) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/textexpanderdemoappswift\/appdelegate\/application(_:open:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/textexpanderdemoappswift\/appdelegate\/application(_:open:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/AppDelegate\/application(_:open:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIApplicationDelegate.application(_:open:options:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"open"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"OpenURLOptionsKey","preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"application(_:open:options:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@TextExpanderDemoAppSwift@objc(cs)AppDelegate(im)application:openURL:options:","modules":[{"name":"TextExpanderDemoAppSwift"}],"navigatorTitle":[{"kind":"identifier","text":"application:openURL:options:"}]},"hierarchy":{"paths":[["doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/AppDelegate"]]},"references":{"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/AppDelegate/application(_:open:options:)":{"role":"symbol","title":"application(_:open:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"application"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":", "},{"kind":"externalParam","text":"open"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"OpenURLOptionsKey","preciseIdentifier":"c:@T@UIApplicationOpenURLOptionsKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/AppDelegate\/application(_:open:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"application:openURL:options:"}],"url":"\/documentation\/textexpanderdemoappswift\/appdelegate\/application(_:open:options:)"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift":{"role":"collection","title":"TextExpanderDemoAppSwift","abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift","kind":"symbol","type":"topic","url":"\/documentation\/textexpanderdemoappswift"},"doc://com.extratone.TextExpanderDemoAppSwift/documentation/TextExpanderDemoAppSwift/AppDelegate":{"role":"symbol","title":"AppDelegate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppDelegate"}],"abstract":[],"identifier":"doc:\/\/com.extratone.TextExpanderDemoAppSwift\/documentation\/TextExpanderDemoAppSwift\/AppDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppDelegate"}],"url":"\/documentation\/textexpanderdemoappswift\/appdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"application:openURL:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:openURL:options:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"application:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIApplication","preciseIdentifier":"c:objc(cs)UIApplication"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"app"},{"kind":"text","text":" "},{"kind":"identifier","text":"openURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1AppDelegate~1application(_:open:options:)\/title","value":"application:openURL:options:"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1AppDelegate~1application(_:open:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"application:openURL:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1AppDelegate\/title","value":"AppDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.extratone.TextExpanderDemoAppSwift~1documentation~1TextExpanderDemoAppSwift~1AppDelegate\/fragments","value":[{"kind":"identifier","text":"AppDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}